#!/usr/bin/env python3
"""
Opening-book tournament: v1.9_engine vs v1.8_engine at fixed depth.

For each of X random opening positions (generated by playing N random moves
from startpos), both engines play both colors. Results are aggregated.

Usage:
  python3 tournament_openings.py [--openings N] [--depth D] [--moves M]
                                  [--opening-plies P] [--benchmark]
                                  [--seed S]

  --openings N      Number of opening positions (default: auto-timed)
  --depth D         Search depth for both engines (default: 10)
  --moves M         Max half-moves per game before draw (default: 200)
  --opening-plies P Random moves to play before starting (default: 10)
  --benchmark       Time 2 games and report seconds/game, then exit
  --seed S          Random seed for reproducibility (default: 42)
  --hours H         Target hours for auto X calculation (default: 7.5)
"""

import argparse
import chess
import chess.pgn
import io
import os
import random
import subprocess
import sys
import time

ENGINE_V20 = None  # set from args.engine1
ENGINE_V19 = None  # set from args.engine2

# ── UCI engine wrapper ────────────────────────────────────────────────────────

class Engine:
    def __init__(self, path, name):
        self.name = name
        self.proc = subprocess.Popen(
            [path],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True, bufsize=1,
        )
        self._send("uci")
        self._read_until("uciok")
        self._send("ucinewgame")
        self._send("isready")
        self._read_until("readyok")

    def _send(self, cmd):
        self.proc.stdin.write(cmd + "\n")
        self.proc.stdin.flush()

    def _read_until(self, token):
        lines = []
        while True:
            line = self.proc.stdout.readline().strip()
            if line:
                lines.append(line)
            if token in line:
                return lines

    def get_move(self, fen, depth, movetime=0):
        self._send(f"position fen {fen}")
        if movetime > 0:
            self._send(f"go movetime {movetime}")
        else:
            self._send(f"go depth {depth}")
        lines = self._read_until("bestmove")
        for line in lines:
            if line.startswith("bestmove"):
                parts = line.split()
                if len(parts) >= 2 and parts[1] not in ("(none)", "0000"):
                    return parts[1]
        return None

    def new_game(self):
        self._send("ucinewgame")
        self._send("isready")
        self._read_until("readyok")

    def quit(self):
        try:
            self._send("quit")
            self.proc.wait(timeout=3)
        except Exception:
            self.proc.kill()


# ── Opening generation ────────────────────────────────────────────────────────

def generate_opening(plies, rng):
    """Play `plies` random legal moves from startpos. Return FEN."""
    board = chess.Board()
    for _ in range(plies):
        legal = list(board.legal_moves)
        if not legal:
            break
        move = rng.choice(legal)
        board.push(move)
        if board.is_game_over():
            board.pop()
            break
    return board.fen()


# ── Single game ───────────────────────────────────────────────────────────────

def play_game(white_engine, black_engine, start_fen, depth, max_moves, movetime=0):
    """
    Play one game from start_fen.
    Returns: 1.0 (white wins), 0.5 (draw), 0.0 (black wins)
    """
    board = chess.Board(start_fen)

    for _ in range(max_moves):
        if board.is_game_over(claim_draw=True):
            break
        engine = white_engine if board.turn == chess.WHITE else black_engine
        move_uci = engine.get_move(board.fen(), depth, movetime)
        if move_uci is None:
            break
        try:
            move = chess.Move.from_uci(move_uci)
        except ValueError:
            break
        if move not in board.legal_moves:
            break
        board.push(move)

    result = board.result(claim_draw=True)
    if result == "1-0":
        return 1.0
    elif result == "0-1":
        return 0.0
    else:
        return 0.5


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--openings",      type=int,   default=0)
    parser.add_argument("--depth",         type=int,   default=10)
    parser.add_argument("--moves",         type=int,   default=200)
    parser.add_argument("--opening-plies", type=int,   default=10, dest="plies")
    parser.add_argument("--benchmark",     action="store_true")
    parser.add_argument("--seed",          type=int,   default=42)
    parser.add_argument("--hours",         type=float, default=7.5)
    parser.add_argument("--movetime",      type=int,   default=0,
                        help="ms per move (overrides --depth if set)")
    parser.add_argument("--engine1",       type=str,   default="./vTest_engine",
                        help="Path to engine 1 (new/test)")
    parser.add_argument("--engine2",       type=str,   default="./v2.1_engine",
                        help="Path to engine 2 (baseline)")
    args = parser.parse_args()

    rng = random.Random(args.seed)

    e1_path = args.engine1
    e2_path = args.engine2
    e1_name = e1_path.lstrip("./").replace("_engine", "")
    e2_name = e2_path.lstrip("./").replace("_engine", "")

    print(f"Starting engines...", flush=True)
    v22 = Engine(e1_path, e1_name)
    v21 = Engine(e2_path, e2_name)
    print(f"  engine1 ({e1_name}): {e1_path}", flush=True)
    print(f"  engine2 ({e2_name}): {e2_path}", flush=True)
    tc_str = f"movetime {args.movetime}ms" if args.movetime > 0 else f"depth {args.depth}"
    print(f"  TC: {tc_str}  Max half-moves: {args.moves}  Opening plies: {args.plies}", flush=True)

    # ── Benchmark: time 2 games, report and exit ──────────────────────────────
    if args.benchmark:
        print("\nBenchmark mode: timing 2 games (1 opening, both colors)...", flush=True)
        fen = generate_opening(args.plies, rng)
        print(f"  Opening FEN: {fen}", flush=True)

        t0 = time.time()
        r1 = play_game(v22, v21, fen, args.depth, args.moves, args.movetime)
        v22.new_game(); v21.new_game()
        r2 = play_game(v21, v22, fen, args.depth, args.moves, args.movetime)
        elapsed = time.time() - t0

        v22.quit(); v21.quit()
        print(f"  Game 1 (v22=W): {r1}", flush=True)
        print(f"  Game 2 (v22=B): {1.0 - r2}", flush=True)
        print(f"  Time for 2 games: {elapsed:.1f}s  ({elapsed/2:.1f}s/game)", flush=True)
        secs_per_pair = elapsed

        for target_h in [7.5, 8.0]:
            x = int(target_h * 3600 / secs_per_pair * 0.92)  # 8% buffer
            print(f"  Openings for {target_h}h: ~{x}", flush=True)
        return

    # ── Auto-calculate openings if not specified ──────────────────────────────
    if args.openings == 0:
        print("\nAuto-timing: running 1 opening pair to estimate speed...", flush=True)
        fen = generate_opening(args.plies, rng)
        t0 = time.time()
        play_game(v22, v21, fen, args.depth, args.moves, args.movetime)
        v22.new_game(); v21.new_game()
        play_game(v21, v22, fen, args.depth, args.moves, args.movetime)
        secs_per_pair = time.time() - t0
        args.openings = max(1, int(args.hours * 3600 / secs_per_pair * 0.92))
        print(f"  {secs_per_pair:.1f}s per opening pair → {args.openings} openings for {args.hours}h", flush=True)
        rng = random.Random(args.seed)  # reset so openings are reproducible

    # ── Generate all opening positions up-front ───────────────────────────────
    print(f"\nGenerating {args.openings} opening positions ({args.plies} random plies each)...", flush=True)
    openings = [generate_opening(args.plies, rng) for _ in range(args.openings)]

    # ── Tournament ────────────────────────────────────────────────────────────
    print(f"\n{'='*65}", flush=True)
    print(f"  {e1_name} vs {e2_name} — {args.openings} openings × 2 colors = {args.openings*2} games", flush=True)
    print(f"  TC: {tc_str}   Opening plies: {args.plies}", flush=True)
    print(f"{'='*65}", flush=True)
    print(f"{'Game':>5}  {'Opening':>7}  {e1_name+' Color':>12}  {'Result':>8}  "
          f"{e1_name+' Score':>12}  {'W':>4} {'D':>4} {'L':>4}  Elapsed", flush=True)
    print(f"{'-'*65}", flush=True)

    v22_score = 0.0
    wins = draws = losses = 0
    start_time = time.time()
    game_num = 0

    for i, fen in enumerate(openings):
        for v22_is_white in [True, False]:
            game_num += 1
            if v22_is_white:
                white_e, black_e = v22, v21
                color_str = "White"
            else:
                white_e, black_e = v21, v22
                color_str = "Black"

            result_white = play_game(white_e, black_e, fen, args.depth, args.moves, args.movetime)

            # Score from v22's perspective
            if v22_is_white:
                v22_result = result_white
            else:
                v22_result = 1.0 - result_white

            v22_score += v22_result

            if v22_result == 1.0:
                wins += 1; res_str = "Win"
            elif v22_result == 0.5:
                draws += 1; res_str = "Draw"
            else:
                losses += 1; res_str = "Loss"

            elapsed = time.time() - start_time
            total_games = args.openings * 2
            eta = elapsed / game_num * (total_games - game_num) if game_num > 0 else 0

            print(f"{game_num:>5}  {i+1:>7}  {color_str:>9}  {res_str:>8}  "
                  f"{v22_score:>12.1f}  {wins:>4} {draws:>4} {losses:>4}  "
                  f"{elapsed/3600:.2f}h  ETA {eta/3600:.2f}h", flush=True)

            v22.new_game()
            v21.new_game()

    # ── Final summary ─────────────────────────────────────────────────────────
    total = game_num
    elapsed = time.time() - start_time
    pct = 100 * v22_score / total if total > 0 else 0

    print(f"\n{'='*65}", flush=True)
    print(f"  FINAL RESULT — {e1_name} vs {e2_name}  ({total} games)", flush=True)
    print(f"  {e1_name}: {wins}W / {draws}D / {losses}L  =  {v22_score:.1f}/{total}  ({pct:.1f}%)", flush=True)
    print(f"  Elapsed: {elapsed/3600:.2f}h", flush=True)
    print(f"{'='*65}", flush=True)

    v22.quit()
    v21.quit()


if __name__ == "__main__":
    main()
